### ISSUE TITLE
project: update infrastructure for bower/amd usage

### ISSUE THREAD

**Issue by x1B** [LaxarJS/ax-developer-tools-widget#17]
For LaxarJS/laxar#179 and LaxarJS/laxar#225 to fully work, we need to update the widget infrastructure.

The _widget.json_ should use the _internal name:_ `ax-developer-tools-widget`.

The _bower.json_ should use the _fully qualified name:_ `laxar-developer-tools-widget`.

This makes widgets work exactly like controls.

**Comment by jpommerening** [comment]
Fixed in `master` -> `release-1.3.x` (`1.3.0`)
