### ISSUE TITLE
travis-build for LaxarJS v1.0.0 broken

### ISSUE THREAD

**Issue by x1B** [LaxarJS/ax-developer-tools-widget#30]
For some reason, bower-installing laxar#v1.0.0 fails with an AngularJS version conflict. The .travis.yml entry has been commented out for now.

**Comment by jpommerening** [comment]
I'll look into this

**Comment by jpommerening** [comment]
Okay first try did not work. But apparently the problem can be fixed by adding resolutions to the `bower.json` file.

So instead of `bower install`ing the LaxarJS version to test, the build should write the desired versions to the `bower.json` file and call `bower install` without any parameters.

**Comment by jpommerening** [comment]
Fixed in LaxarJS/grunt-laxar#91. The `bower install …` line inside `.travis.yml` is now a no-op. We can remove it in future widgets but it does no harm still being there.
