### ISSUE TITLE
late listener registration causes WARN message

### ISSUE THREAD

**Issue by x1B** [LaxarJS/ax-developer-tools-widget#49]
Since v2.0.1: There is an error in the listener initialization causing problems with the page tooling API.

**Comment by x1B** [comment]
https://github.com/LaxarJS/ax-developer-tools-widget/blob/master/ax-developer-tools-widget.js#L114

must be moved up.

**Comment by jonaswjs** [comment]
Fixed on `master` (`v2.1.0`) and on `release-2.0.x` (`v2.0.3`).
